[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.mbstring",
    "php82Extensions.pdo_sqlite",
    "php82Extensions.sqlite3",
    "php82Extensions.pdo_mysql",
    "php82Extensions.mysqlnd",
    "php82Extensions.curl",
    "composer",
    "nodejs_20"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
